-- V2: 도메인 강화 (priority) + 쿼터 + Outbox + 이벤트 이력
-- 운영(PostgreSQL) 에서는 partial index (특정 조건의 row 만 인덱싱) 로 디스크 절약
-- 가능 (예: WHERE status IN (...) — active 상태 row 만). H2 는 partial index 미지원
-- 이라 V2 는 일반 인덱스로만 작성. PG 별 추가 최적화는 V3+ 에서.

ALTER TABLE jobs ADD COLUMN priority VARCHAR(16) NOT NULL DEFAULT 'NORMAL';

-- 디스패처가 우선순위 + 생성시각 순으로 큐에서 꺼낼 때 사용
CREATE INDEX idx_jobs_dispatch_order ON jobs (priority, created_at);

-- 쿼터 검사용 (owner 별 active job 카운트 — 사용자가 동시에 띄운 잡 개수와 GPU 합계
-- 를 한 번의 SUM/COUNT 쿼리로 구하기 위함)
CREATE INDEX idx_jobs_owner_status ON jobs (owner, status);

CREATE TABLE user_quotas (
    owner               VARCHAR(128) PRIMARY KEY,
    max_concurrent_jobs INT          NOT NULL,
    max_gpu_count       INT          NOT NULL,
    updated_at          TIMESTAMP    NOT NULL
);

-- 트랜잭션 안전 이벤트 발행 (Outbox 패턴 — DB 안에 발신함 테이블을 두고 도메인 변경
-- 과 같은 트랜잭션에 INSERT, 별도 relay 가 polling 으로 Kafka 발행)
CREATE TABLE outbox (
    id              UUID         PRIMARY KEY,
    aggregate_type  VARCHAR(128) NOT NULL,
    aggregate_id    VARCHAR(128) NOT NULL,
    event_type      VARCHAR(128) NOT NULL,
    payload         TEXT         NOT NULL,
    created_at      TIMESTAMP    NOT NULL,
    published_at    TIMESTAMP
);

CREATE INDEX idx_outbox_unpublished ON outbox (published_at, created_at);

-- Job 이력 (append-only — 한 번 쓰면 수정·삭제 안 함)
CREATE TABLE job_events (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id       UUID         NOT NULL,
    event_type   VARCHAR(32)  NOT NULL,
    payload      TEXT,
    occurred_at  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_job_events_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE
);

CREATE INDEX idx_job_events_job_occurred ON job_events (job_id, occurred_at);
